### ISSUE TITLE
Exports have been changed in 4.4

### ISSUE THREAD

**Issue by alekitto** [ujjwalguptaofficial/JsStore#285]
# Description 

After upgrading the library to 4.4.1 from 4.3.10, I have compilation errors in my React + typescript application similar to:

```
export 'Connection' (imported as 'Connection') was not found in 'jsstore' (possible exports: JsStore)
export 'DATA_TYPE' (imported as 'DATA_TYPE') was not found in 'jsstore' (possible exports: JsStore)
```

**Comment by Delagen** [comment]
Because now it expors JSStore property, but typings seems not changed

Awaiting for update

**Comment by ujjwalguptaofficial** [comment]
ohk let me see, it might be due to webpack 5 upgrade

**Comment by ujjwalguptaofficial** [comment]
fixed in v - 4.4.3. @Delagen @alekitto please have a look.

**Comment by alekitto** [comment]
Seems ok now. Thank you!
